### ISSUE TITLE
Skapa filstruktur för systemtester

### ISSUE THREAD

**Issue by dsteenie** [dsteenie/produkt-api-master#15]

**Comment by BornTheWrongAnimal** [comment]
VI har redan dependencies i pom. filen, så inget mer behövs där
	
Jag skapar alla filer som behövs för att komma igång, detta gör jag under src- est-java där våra enhetstester ligger
	
Jag skapar en Runner
	
Jag skapar en mapp för resources och en mapp för features
	
Jag skapar en tom Feature fil som en första mall
	
Jag skapar en Testdefinition class
	
Jag skapar en första test så att jag kan testa att det funkar i Github actions
	
felsöker om det blir problem med chrome driver,  glue eller annat
