### ISSUE TITLE
Skapa systemtest för webshop: Kontroll av varukorgen

### ISSUE THREAD

**Issue by dsteenie** [dsteenie/produkt-api-master#38]
- Skriv Gherkin-scenarios  
- Implementera Selenium-tester  
- Automatisera testkörningen i CI/CD

**Comment by BornTheWrongAnimal** [comment]
Har vi täckt denna med testen nedan från förra sprint?         

  ##Verify total amount rounding in cart - Pierre Nilsson
  @acceptance
  Scenario: Verify total amount rounding in cart
    Given I am on the shop pagepierre
    When I add "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops" to the cart
    And I add "Mens Casual Premium Slim Fit T-Shirts" to the cart
    When I navigate to the checkout page
    Then the total amount in the cart should be "$132.25"

I så fall kan vi markera detta som done
